TILE_ATTRIBUTES = {
    "player": ("open", "craft"),
    "sapling": ("grow"),
    "treeling": ("grow", "no_pickup"),
    "tree": ("no_pickup"),
    "spore": ("grow"),
    "mushroom": ("eat"),
    "carrot": ("grow", "eat"),
    "carroot": ("no_pickup"),
    "rabbit child": ("grow", "move", "no_pickup"),
    "rabbit adult": ("move", "no_pickup"),
    "rabbit hole": ("unbreak",),
    "roasted mushroom": ("eat",),
    "mushroom stew": ("eat",),
    "workbench": ("open", "craft"),
    "campfire": ("open", "craft", "light"),
    "sawbench": ("open", "craft", "multi"),
    "manual press": ("open", "craft", "multi"),
    "small crate": ("open", "store"),
    "small barrel": ("open", "store"),
    "wooden cabin": ("enter", "multi", "wood"),
    "wooden door": ("exit", "unbreak"),
    "wooden bed": ("sleep", "multi"),
    "rabbit meat": ("eat",),
    "roasted rabbit meat": ("eat",),
    "left": ("point", "unbreak"),
    "up": ("point", "unbreak"),
    "junk": ("no_pickup",),
    "corpse": ("no_pickup",),
    "obelisk": ("multi", "unbreak"),
    "big rock": ("multi", "no_pickup"),
}
RECIPES = {
    "player": [
        (("workbench", 1), [("wood", 4), ("flint", 2)]),
        (("stick", 4), [("wood", 2)]),
    ],
    "workbench": [
        (("flint sword", 1), [("stick", 2), ("flint", 4), ("ice", 1)]),
        (("flint axe", 1), [("stick", 3), ("flint", 4)]),
        (("flint pickaxe", 1), [("stick", 3), ("flint", 4)]),
        (("flint shovel", 1), [("stick", 2), ("flint", 3)]),
        (("campfire", 1), [("wood", 5), ("flint", 2), ("stick", 6)]),
        (("bowl", 4), [("wood", 3), ("stick", 2)]),
        (("wood pulp", 2), [("wood", 3), ("water", 2)]),
        (("flint hammer", 1), [("stick", 4), ("rock", 2), ("flint", 3)]),
        (("manual press", 1), [("workbench", 1), ("flint hammer", 1)]),
        (("sawbench", 1), [("workbench", 1), ("flint axe", 2)]),
    ],
    "campfire": [
        (("roasted mushroom", 1), [("mushroom", 1), ("stick", 1)]),
        (("water", 2), [("ice", 1), ("bowl", 2)]),
        (("mushroom stew", 2), [("mushroom", 3), ("carrot", 1), ("water", 2)]),
        (("stone", 1), [("rock", 1)]),
        (("brick", 2), [("clay", 1)]),
        (("roasted rabbit meat", 1), [("rabbit meat", 1)]),
    ],
    "manual press": [
        (("blue dye", 2), [("bluebell", 2), ("water", 1), ("bowl", 1)]),
        (("paper", 2), [("wood pulp", 3)]),
        (("blueprint", 1), [("paper", 3), ("blue dye", 2)]),
    ],
    "sawbench": [
        (("stick", 7), [("wood", 3)]),
        (("small crate", 1), [("wood", 6), ("stick", 4)]),
        (("small barrel", 1), [("wood", 6), ("stick", 4)]),
        (("stone brick", 2), [("stone", 3)]),
        (("wooden cabin", 1), [("wood", 16), ("brick", 6)]),
        (("wooden bed", 1), [("wood", 10), ("blue dye", 3), ("rabbit fur", 2)]),
    ],
}
TOOL_REQUIRED = {
    "player": "sword",
    "sapling": "shovel",
    "treeling": "axe",
    "tree": "axe",
    "wood": "axe",
    "spore": "shovel",
    "mushroom": "axe",
    "flint": "pickaxe",
    "ice": "pickaxe",
    "stick": "axe",
    "campfire": "axe",
    "carroot": "shovel",
    "carrot": "shovel",
    "rock": "pickaxe",
    "big rock": "pickaxe",
    "clay": "shovel",
    "stone": "pickaxe",
    "stone brick": "pickaxe",
    "brick": "pickaxe",
    "rabbit child": "sword",
    "rabbit adult": "sword",
    "sawbench": "axe",
    "wood pulp": "shovel",
    "manual press": "pickaxe",
    "bluebell": "shovel",
    "small crate": "axe",
    "wooden cabin": "axe",
}
TOOL_EFFICIENCY = {"flint": 1, "rock": 2}
MULTI_TILES = {
    "sawbench": (2, 1),
    "manual press": (2, 1),
    "wooden cabin": (4, 3),
    "wooden bed": (1, 2),
    "obelisk": (1, 2),
    "big rock": (2, 2),
}
STORAGE = {"small crate": (9, 48), "small barrel": (1, 512)}
FOOD = {
    "mushroom": 1,
    "carrot": 2,
    "roasted mushroom": 3,
    "mushroom stew": 6,
    "rabbit meat": 1,
    "roasted rabbit meat": 4,
}
GROW_TILES = {
    "sapling": ("treeling", {"wood": 2, "sapling": 1}),
    "treeling": ("tree", {"wood": 4, "sapling": 2}),
    "spore": ("mushroom", {"spore": 2, "mushroom": 1}),
    "carrot": ("carroot", {"carrot": 2}),
    "rabbit child": ("rabbit adult", {"rabbit fur": 1, "rabbit meat": 2}),
}
GROW_CHANCE = {
    "sapling": 5000,
    "treeling": 10000,
    "spore": 7500,
    "carrot": 10000,
    "rabbit child": 12500,
}
TILE_RESISTANCE = {
    "clay": 1,
    "rock": 1,
    "ice": 1,
    "tree": 1,
    "rabbit adult": 1,
    "sawbench": 1,
    "manual press": 1,
    "wooden cabin": 1,
    "stone": 1,
    "stone brick": 1,
    "brick": 1,
    "big rock": 2,
}
TILE_HEALTH = {
    "big rock": 45,
    "blue dye": 6,
    "bluebell": 10,
    "blueprint": 8,
    "bowl": 6,
    "brick": 12,
    "campfire": 8,
    "carroot": 8,
    "carrot": 4,
    "clay": 12,
    "corpse": 1,
    "flint axe": 6,
    "flint hammer": 10,
    "flint pickaxe": 6,
    "flint shovel": 6,
    "flint sword": 6,
    "flint": 16,
    "ice": 12,
    "junk": 1,
    "left": 1,
    "manual press": 12,
    "mushroom stew": 6,
    "mushroom": 10,
    "obelisk": 1,
    "paper": 8,
    "player": 20,
    "rabbit adult": 10,
    "rabbit child": 6,
    "rabbit fur": 8,
    "rabbit hole": 1,
    "rabbit meat": 6,
    "roasted mushroom": 8,
    "roasted rabbit meat": 10,
    "rock": 20,
    "sapling": 4,
    "sawbench": 12,
    "small barrel": 10,
    "small crate": 10,
    "spore": 4,
    "stick": 4,
    "stone brick": 16,
    "stone": 16,
    "tree": 15,
    "treeling": 9,
    "up": 1,
    "water": 8,
    "wood pulp": 6,
    "wood": 4,
    "wooden bed": 12,
    "wooden cabin": 42,
    "wooden door": 1,
    "workbench": 5,
}
