TILE_ATTRIBUTES = {
    "sapling": ("grow",),
    "treeling": ("grow", "no_pickup"),
    "tree": ("no_pickup"),
    "spore": ("grow",),
    "mushroom": ("eat"),
    "carrot": ("grow", "eat"),
    "carroot": ("no_pickup"),
    "rabbit child": ("grow", "move", "no_pickup"),
    "rabbit adult": ("move", "no_pickup"),
    "roasted mushroom": ("eat",),
    "mushroom stew": ("eat",),
    "workbench": ("open", "craft"),
    "campfire": ("open", "craft", "light"),
    "sawbench": ("open", "craft", "multi"),
    "manual press": ("open", "craft", "multi"),
    "small crate": ("open", "store"),
    "small barrel": ("open", "store"),
    "wooden cabin": ("enter", "multi"),
    "wooden door": ("exit",),
    "wooden bed": ("sleep", "multi"),
    "rabbit meat": ("eat",),
    "roasted rabbit meat": ("eat",),
    "big rock": ("multi", "no_pickup"),
    "mushroom hut": ("multi", "enter"),
    "mushroom shaper": ("open", "craft"),
    "coal ore": ("no_pickup"),
    # Special tiles
    "left": ("point", "no_pickup"),
    "up": ("point", "no_pickup"),
    "player": ("open", "craft", "no_pickup"),
    "junk": ("no_pickup",),
    "corpse": ("no_pickup",),
    "obelisk": ("multi", "no_pickup"),
}
TOOL_REQUIRED = {
    "player": "sword",
    "sapling": "shovel",
    "treeling": "axe",
    "tree": "axe",
    "wood": "axe",
    "spore": "shovel",
    "mushroom": "axe",
    "flint": "pickaxe",
    "ice": "pickaxe",
    "stick": "axe",
    "campfire": "axe",
    "carroot": "shovel",
    "carrot": "shovel",
    "rock": "pickaxe",
    "big rock": "pickaxe",
    "clay": "shovel",
    "stone": "pickaxe",
    "stone brick": "pickaxe",
    "brick": "pickaxe",
    "rabbit child": "sword",
    "rabbit adult": "sword",
    "sawbench": "axe",
    "wood pulp": "shovel",
    "manual press": "pickaxe",
    "bluebell": "shovel",
    "small crate": "axe",
    "wooden cabin": "axe",
    "mushroom hut": "axe",
    "mushroom block": "axe",
    "mushroom shaper": "axe",
    "dirt": "shovel",
    "coal ore": "pickaxe",
    "coal": "pickaxe",
}
TOOL_EFFICIENCY = {"flint": 1, "rock": 2}
MULTI_TILES = {
    "sawbench": (2, 1),
    "manual press": (2, 1),
    "wooden cabin": (4, 3),
    "wooden bed": (1, 2),
    "obelisk": (1, 2),
    "big rock": (2, 2),
    "mushroom hut": (3, 2),
}
STORAGE = {"small crate": (9, 48), "small barrel": (1, 512)}
FOOD = {
    "mushroom": 1,
    "carrot": 2,
    "roasted mushroom": 3,
    "mushroom stew": 6,
    "rabbit meat": 1,
    "roasted rabbit meat": 4,
}
GROW_TILES = {
    "sapling": ("treeling", {"wood": 2, "sapling": 1}),
    "treeling": ("tree", {"wood": 4, "sapling": 2}),
    "spore": ("mushroom", {"spore": 2, "mushroom": 1}),
    "carrot": ("carroot", {"carrot": 2}),
    "rabbit child": ("rabbit adult", {"rabbit fur": 1, "rabbit meat": 2}),
}
GROW_CHANCE = {
    "sapling": 5000,
    "treeling": 10000,
    "spore": 7500,
    "carrot": 10000,
    "rabbit child": 12500,
}
RESISTANCE = {
    "clay": 1,
    "rock": 1,
    "tree": 1,
    "rabbit adult": 1,
    "sawbench": 1,
    "manual press": 1,
    "wooden cabin": 1,
    "stone": 1,
    "stone brick": 1,
    "brick": 1,
    "big rock": 2,
    "mushroom hut": 2,
    "mushroom block": 1,
    "mushroom shaper": 2,
    "ice": 1,
    "coal ore": 2,
    "coal": 1,
}
UNBREAK = ("rabbit hole", "wooden door", "left", "up", "obelisk")
FLOOR = ("void", "ice", "wood floor", "dirt", "mushroom floor")
FLOOR_UNBREAK = ("void",)
FLOOR_TYPE = {"void": "block", "ice": "block", "dirt": "soil"}