ATTRIBUTES = {
    "big rock": {"no_pickup"},
    "bonsai pot": {"open", "machine"},
    "campfire": {"open", "craft", "light"},
    "carrot": {"grow"},
    "carroot": {"no_pickup"},
    "coal ore": {"no_pickup"},
    "compost": {"fertilize"},
    "composter": {"open", "machine", "value"},
    "fertilizer": {"fertilize"},
    "furnace": {"open", "machine", "value"},
    "glass key": {"key"},
    "glass lock": {"lock"},
    "manual press": {"open", "craft"},
    "masonry bench": {"open", "craft"},
    "mushroom shaper": {"open", "craft"},
    "rabbit adult": {"rabbit", "no_pickup"},
    "rabbit child": {"grow", "rabbit", "no_pickup"},
    "sapling": {"grow"},
    "sawbench": {"open", "craft"},
    "small barrel": {"open", "store"},
    "small crate": {"open", "store"},
    "spore": {"grow"},
    "torch": {"light"},
    "tree": {"no_pickup"},
    "treeling": {"grow", "no_pickup"},
    "wooden bed": {"sleep"},
    "wooden table": {"store", "table"},
    "workbench": {"open", "craft"},

    # Special tiles
    "left": {"point", "no_pickup"},
    "up": {"point", "no_pickup"},
    "player": {"open", "craft", "no_pickup"},
    "junk": {"no_pickup"},
    "corpse": {"no_pickup"},
    "obelisk": {"no_pickup"},
}