DESCRIPTION = {
    "amethyst axe": "+3 damage to wooden materials",
    "amethyst hammer": "+3 damage to sticky materials",
    "amethyst pickaxe": "+3 damage to rocky materials",
    "amethyst shovel": "+3 damage to soft materials",
    "amethyst sword": "+3 damage to enemies",
    "amethyst rune": "+1 to mana",
    "anklet of the tree": "+5% to base movement speed",
    "boots": "+12% to base movement speed",
    "citrine rune": "+2 to mana",
    "copper axe": "+3 damage to wooden materials",
    "copper hammer": "+3 damage to sticky materials",
    "copper needle": "+3 damage to furlike materials and may shear certain things",
    "copper pickaxe": "+3 damage to rocky materials",
    "copper shovel": "+3 damage to soft materials",
    "copper sword": "+3 damage to enemies",
    "copper wrench": "May rotate certain things",
    "flint axe": "+1 damage to wooden materials",
    "flint hammer": "+1 damage to sticky materials",
    "flint pickaxe": "+1 damage to rocky materials",
    "flint shovel": "+1 damage to soft materials",
    "flint sword": "+1 damage to enemies",
    "lava rune": "*0.8 and then +5 to mana",
    "rock axe": "+2 damage to wooden materials",
    "rock hammer": "+2 damage to sticky materials",
    "rock pickaxe": "+2 damage to rocky materials",
    "rock shovel": "+2 damage to soft materials",
    "rock sword": "+2 damage to enemies",
    "water axe": "+2 damage to wooden materials",
    "water hammer": "+2 damage to sticky materials",
    "water pickaxe": "+2 damage to rocky materials",
    "water shovel": "+2 damage to soft materials",
    "water sword": "+2 damage to enemies",
}