DESCRIPTION = {
    "amethyst dirt": "Soil of strength 1.4",
    "amethyst rune": "+1 to mana",
    "anklet of the tree": "+5% to base movement speed",
    "boots": "+12% to base movement speed",
    "bronze harvester": "Connect four in the corners to harvest plants",
    "citrine rune": "+2 to mana",
    "coal block": "-1 heat; adjacent to min. 1 connector",
    "copper axe": "+3 damage to wooden materials",
    "copper boiler": "Machine to evaporate water; Bct: 10s",
    "copper hammer": "+3 damage to sticky materials",
    "copper needle": "+3 damage to threads and shearing",
    "copper pickaxe": "+3 damage to rocky materials",
    "copper pit": "Put in the ground to eventually get copper",
    "copper shovel": "+3 damage to soft materials",
    "copper sword": "+3 damage to enemies",
    "copper tank": "+2 heat; +1 efficiency; adjacent to min. 2 coal blocks",
    "copper wrench": "May rotate certain things",
    "crushing chamber": "+1 efficiency; adjacent to 4 crushing wheel",
    "crushing wheel": "+1 heat; adjacent to min. 1 coal block",
    "dirt": "Soil of strength 1",
    "flint axe": "+1 damage to wooden materials",
    "flint hammer": "+1 damage to sticky materials",
    "flint pickaxe": "+1 damage to rocky materials",
    "flint shovel": "+1 damage to soft materials",
    "flint sword": "+1 damage to enemies",
    "furnace": "Machine for smelting; Bct: 30s",
    "furnace accelerator": "+1 heat; +1 efficiency; adjacent to min. 2 coal blocks",
    "lavastone furnace accelerator": "+1 efficiency; adjacent to 4 furnace accelerator",
    "lava rune": "*0.8 and then +5 to mana",
    "moist dirt": "Soil of strength 1.25",
    "rock axe": "+2 damage to wooden materials",
    "rock hammer": "+2 damage to sticky materials",
    "rock pickaxe": "+2 damage to rocky materials",
    "rock shovel": "+2 damage to soft materials",
    "rock sword": "+2 damage to enemies",
    "sapphire rune": "*1.26 and then -3 to mana",
    "snow": "Soil of strength 0.85",
    "steam crusher": "Machine for crushing; Bct: 30s",
    "steam furnace": "Machine for smelting; Bct: 30s",
    "water axe": "+2 damage to wooden materials",
    "water hammer": "+2 damage to sticky materials",
    "water pickaxe": "+2 damage to rocky materials",
    "water shovel": "+2 damage to soft materials",
    "water sword": "+2 damage to enemies",
}